use stderr in shell intercepts

diff --git a/usr/share/lmc/init/bash b/usr/share/lmc/init/bash
--- a/usr/share/lmc/init/bash
+++ b/usr/share/lmc/init/bash
@@ -12,33 +12,33 @@ command_not_found_handle() {
     if [ -n "$res" ]; then
         if [ $lines -eq 1 ]; then
             mod=$(echo "$res" | cut -d'"' -f4)
-            echo "[lmc] autoloading $mod.."
+            echo "[lmc] autoloading $mod.." >&2
             module load $mod && $@
         else
-            echo "[lmc] select a module to load:"
+            echo "[lmc] select a module to load:" >&2
             num=0
             while read -r line; do
                 mod_root=$(echo $line | cut -d'"' -f2)
                 mod_code=$(echo $line | cut -d'"' -f4)
 
                 num=$((num + 1))
-                printf "\t%d) %s\n" $num "$mod_code"
+                printf "\t%d) %s\n" $num "$mod_code" >&2
             done <<< "$res"
-            printf "[lmc] enter a selection (1-%d, q to abort) [1]: " $num
+            printf "[lmc] enter a selection (1-%d, q to abort) [1]: " $num >&2
             read -r inp
             [ ! -n "$inp" ] && inp=1
             if [ $inp -ge 1 ]; then
                 if [ $inp -le $num ]; then
                     mod=$(echo "$res" | head -n $inp | tail -n1 | cut -d'"' -f4)
-                    echo "[lmc] loading $mod.."
+                    echo "[lmc] loading $mod.." >&2
                     module load $mod && $@
                     exit $?
                 fi
             fi
 
-            echo "[lmc] cancelling.."
+            echo "[lmc] cancelling.." >&2
         fi
     else
-        echo "$1: command not found, no modules found"
+        echo "$1: command not found, no modules found" >&2
     fi
 }
