add lmc installation check in shell inits

diff --git a/share/lmc/init/bash b/share/lmc/init/bash
--- a/share/lmc/init/bash
+++ b/share/lmc/init/bash
@@ -5,6 +5,12 @@
 LMC_PREFIX="$( cd "$(dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/../../../
 
 export PATH=${LMC_PREFIX}/bin:$PATH
+
+if ! type lmc 2>&1 >/dev/null; then
+    echo "[lmc] couldn't find lmc binary, please check it is built"
+    return
+fi
+
 lmc build
 
 if ! type module 2>&1 >/dev/null; then
diff --git a/share/lmc/init/zsh b/share/lmc/init/zsh
--- a/share/lmc/init/zsh
+++ b/share/lmc/init/zsh
@@ -5,6 +5,12 @@
 LMC_PREFIX=$(dirname ${0:a})/../../../
 
 export PATH=${LMC_PREFIX}/bin:$PATH
+
+if ! type lmc 2>&1 >/dev/null; then
+    echo "[lmc] couldn't find lmc binary, please check it is built"
+    return
+fi
+
 lmc build
 
 if ! type module 2>&1 >/dev/null; then
